### ISSUE TITLE
Full testing Monday 6/12 in the afternoon after services switchover

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#107]
## Testing
Using the spreadsheet below, please complete assigned sections and kick off bugs. 
### [create copy of the testing template](https://docs.google.com/spreadsheets/d/1v-K4NWEPyERabHHCMPADI79P-d1FAu2_fqy_dgfngdI/copy)

And save it to [Repository and Digital Curation Shared Docs/TestScripts/completed_scripts](https://docs.google.com/spreadsheets/d/13cWzYMIMRZJ877_5Lbpf8VQNl2628jbq8kWnlsRJM3w/edit?usp=sharing/copy) using YYYYMMMDD_lastname as a filename. 

## Bugs found

For each bug found, add a new github issue to [nulib/avalon](https://github.com/nulib/avalon/issues) and label it "bug". 

Bugs will be triaged and dealt with as necessary. 
## Test on 

media.northwestern.edu

## Example Comment when you're done with a task

Hi, I tested section 1 -- script and notes in:  [link to your copy of testing script here]

FYI I found bugs #1, #1, #1

## Tasks and assignees

- [x] 1. Create private collection 
- [x] 2. Web Ingest an item
- [x] 3. LTI
- [x] 4. Embed
- [x] 5. Batch ingest
- [x] 6. Structural Metadata
- [x] 7. Create group
- [x] 8. Bulk actions
- [x] 9. Search/playback
- [x] 10. Accessibility
- [x] 11. Playback - sticky quality
- [x] 12. Captions
- [x] 13. IP based access control
- [x] 14. Start/end dates for access (Lease)
- [x] 15. Playlists and Items
- [x] 16. Zoom Scrubber

**Comment by jenyoung** [comment]
@egilchrist Not part of the script, but verify that items in your batch upload folder delete after ingest (except the .xslx)

**Comment by davidschober** [comment]
@egilchrist We will be ready to roll after 1:00pm.

**Comment by davidschober** [comment]
@egilchrist feel free to close this out when you're done. I created a new issue for your final problem.

**Comment by egilchrist** [comment]
@jenyoung - You asked me to verify that the items in my batch upload folder delete.  Do you mean the folder on Cyberduck?  If that's what you mean, the assets folder is still in Erin Test and the items are still in the asset folder.

**Comment by jenyoung** [comment]
@mbklein the assets should be moved from the asset folder after ingestion correct?
@egilchrist i was actually thinking of deleting your test collection from AVR itself, but the assets need to be moved as well.

**Comment by ccaizzi** [comment]
@davidschober @mbklein @jenyoung i'm fairly certain mbk told us the assets will remain for the time being.  he potentially was going to move them to a new S3 bucket (@carrick)? are these the masters that will need to get sync'd down to Isilon?

**Comment by davidschober** [comment]
@ccaizzi yes. They're not being removed yet. We will move them to a new s3 bucket. I will create an issue for it. 

With that are we all good with regression?

**Comment by davidschober** [comment]
@ccaizzi yes. They're not being removed yet. We will move them to a new s3 bucket. I will create an issue for it. 

With that are we all good with regression?

@egilchrist can you check off the boxes you tested so we have an idea of scope?

**Comment by egilchrist** [comment]
@davidschober - I'm assuming you mean on testing template?  I went back and put x's by all the items that I was successfully able to test.  Or do you want me to check off the boxes on a different document?

**Comment by davidschober** [comment]
nope that’s what I meant!

**Comment by davidschober** [comment]
Cool. I don't see the checked boxes. Can you hit the ones you tested and feel free to close.

**Comment by davidschober** [comment]
Closing Thanks everyone.
