### ISSUE TITLE
Final Migration of Avalon 4 Content to AWS

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#143]
- [x] Use create date to get everything created in 4 and push it to AWS
- [x] Migrate the 156 pids referenced [here](https://github.com/nulib/avalon/issues/142#issuecomment-308799599)
- [x] Scan for any failed HLS Splits like we did in #123 
- [x] Scan for any duplicate MediaObjects or MasterFile issues as done in #111

**Comment by davidschober** [comment]
@carrickr can you update this issue Monday? I think it's 99% done.

**Comment by carrickr** [comment]
Waiting for #142 to complete, I'll run one final scan and then close this

**Comment by carrickr** [comment]
@mbklein Looks like content is done and we just need to attach and split

**Comment by ccaizzi** [comment]
@carrickr @mbklein is this done?  if so, please close.
