### ISSUE TITLE
Avalon on AWS Checklist

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#19]
## < May 11 (prep work, systems ready)

During this cycle, the rdc team was largely heads down investing, drafting the AWS pilot proposal (https://github.com/nulib/repodev_planning_and_docs/wiki/Avalon-AWS-Pilot-%28Summer-2017%29), and ensuring we could pull this off. 

- [x] Set up another meeting how/why/theory and maps #20
- [x] Dig into AWS Cloud watch / discuss strategy with Devops team #21
- [x] Devops to go over aws cloud formation scripts / Read avalon one/MBK to assist #22
- [x] @mbk creates initial pass of system as part of grant work
- [x] Finalize how auth will work with AWS #23
- [x] Plans for migrating data to AWS #15 

### May 11-21

Discussion with outside folks after a call was made that we could hit our summer session deadline.

- [x] skinning first pass @adamjarling May 11-May 21. 
- [x] System Stable @mbklein May 15
- [x] Migration path decision collections @carrickr  May 15 #15 
- [x] Inform Molly, Alex, and Cecile (Features, redundancy)  (MMLC) @Nic4Images 
- [x] Work with IT Infra to make sure FTP clients (Cyberduck) are available on library machines (Molly and Alex and ours). Email sent from CC to Bob and Marek May 11. @ccaizzi ### May 28-30 (stabilize systems, migrate)
- [x] How we are handling Monitoring/ How we are going to do it #21
- [x] Plans for disaster (e.g. system outages) #24

### May 22 - May 31

During this period we will be moving data and swill start testing/ train users. 

- [x] Move derivatives to Avalon AWS #52
- [x] Migration Frist run @carrickr @mbklein  (May 30) #60 #61 
- [x] Migrate test data, start testing @carrickr #60 #41 #61  
- [x] Set storage to Reduced Redundancy for derivatives #51
- [x] Molly, etc, will need to use FTP for batches.  Ensure it's loaded on system
- [x] text needed About, Help (from current footer and https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+User+Guide), and Contact Us @Nic4Images #62 #63 

### June 1 - June 5

Testing and final migration (if necessary)

- [x] Metadata testing ( @jenyoung ) June 1 -5 #75
- [x]  Final migration of all data and derivatives #61 #30
- [x]  training of Cecile and RDC (train the trainers) June 1 #76
- [x] wire up canvas #65 
- [x] Procedures written on how to deal with emergencies @carrickr @mbklein @d-venckus @Toputnal #79 

### June 5-9

NOTE: DS will be in Italy, Nicole is at a conference. @jenyoung is in charge. 

- [x] Team does full regression testing on production if necessary. #73 (first pass). Testing should be completed after data migration (notice from @carrickr)  and before June 8. 
- [x] Molly and Cecile test June 8 (on production) @jenyoung and @ccaizzi to triage.
- [x] Freeze of adding content to AVR until Monday June 12.

### June 12-16

Intercession. During this week we will do final production testing, ensuring that canvas is working, etc. In addition, we will ensure that all of our users that need access have it. 

- [x] Production Testing (Spot check permissions, etc) Erin will be conducting June 12 PM along with Course Reserves and  Media and Design (Cecile) #73 @jenyoung 
- [x] New material is **only** being put in Avalon
- [x] Final sign off (DS/CC/JY)
- [x]  Switch DNS / Golive #77 #102 
- [x] Firedrill for Avalon (Carrick to act as chaos monkey)

### June 19 Go live. 

- [x] attach outlying master files https://github.com/nulib/avalon/issues/142
- [x] Final, final migration of any new data <https://github.com/nulib/avalon/issues/144> <https://github.com/nulib/avalon/issues/143>
- [x] verify about text is working <https://github.com/nulib/avalon/issues/62>
- [x] Final splits of HLS <https://github.com/nulib/avalon/issues/123>

### Post Go-Live

- [ ] Evaluate very large derivatives #53
- [ ] Cost analysis for 12 months/ Dig into ways to save money/ After kickoff #26
- [ ] Lifecycle management of digital objects 
    (e.g. pushing transcoded objects into glacier
- [ ] Monitoring for improvements in speed / bulletproofness. Continue to offer suggestions
- [ ] Load tests / how do we get a realistic figure #27
- [ ]  Plans for syncing master files from AWS  #25
- [ ] improvements #28 
- [ ] Celebratory Donuts/Beer/ and fame and glory

## Risks -- any of these can put us off time

- Migration goes bad/ off
- Training doesn't go well (users are confused, things don't work)
- Canvas integration fails
- Authentication stops working
- Devops has issues with security, etc.

**Comment by carrickr** [comment]
I would propose we move the Firedrill (under the June 1 through 5 tasks) to post June 12th and do it on either the dev stack or a clone of the production stack.  I don't think I can afford to randomly blow up the stack and deny jyo et al the ability to verify data whilst dev-ops fixes it.

**Comment by davidschober** [comment]
Agreed. Moving it.
