### ISSUE TITLE
Full Regression Testing 6.3

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#265]
Using the spreadsheet below, please complete assigned sections and kick off bugs. 
### [create copy of the testing template](https://docs.google.com/spreadsheets/d/1xOsh_Cg47UwHV3h95zcVPPpnB0T43arWnnZvhLMQFJc/edit#gid=188479199/copy)

And save it to [Repository and Digital Curation Shared Docs/TestScripts/completed_scripts](https://drive.google.com/drive/folders/0B3iiRmWEFfdYUTBGcmR4R3R2dVU) using YYYYMMMDD_lastname as a filename. 

## Bugs found

For each bug found, add a new github issue to [nulib/avalon](https://github.com/nulib/avalon/issues) and label it "bug". 

Bugs will be triaged and dealt with as necessary. 

## Test on 

http://avr.repo.rdc-staging.library.northwestern.edu

## Example Comment when you're done with a task

Hi, I tested section 1 -- script and notes in:  [link to your copy of testing script here]

FYI I found bugs #1, #1, #1

## Tasks and assignees - @Nic4images @egilchrist and @druParrish will be testing November 2

- [ ] 1. Create private collection 
- [ ] 2. Web Ingest an item
- [ ] 3. LTI
- [ ] 4. Embed
- [ ] 5. Batch ingest
- [ ] 6. Structural Metadata
- [ ] 7. Create group
- [ ] 8. Bulk actions
- [ ] 9. Search/playback
- [ ] 10. Accessibility
- [ ] 11. Playback - sticky quality
- [ ] 12. Captions
- [ ] 13. IP based access control
- [ ] 14. Start/end dates for access (Lease)
- [ ] 15. Playlists and Items
- [ ] 16. Zoom Scrubber

## Special consideration:

Verify that the contact us form works. 

http://media.northwestern.edu/comments

**Comment by davidschober** [comment]
This will occur Nov 2. by molly, alex, etc.

**Comment by davidschober** [comment]
The remainder of this will occur Friday.

**Comment by davidschober** [comment]
Got stuck with batch emails not working.

**Comment by davidschober** [comment]
Good to go. Course reserves had a couple of questions.
