### ISSUE TITLE
NU Avalon - UI Northwestern Branding

### ISSUE THREAD

**Issue by adamjarling** [nulib/avalon#32]
### Description
Apply Northwestern branding styles to NU's Avalon 6 application

### Done Looks Like
- [x] #34 Apply NU Branding Sass/CSS to Rails app
- [x] #35 Header & footer
- [x] #36 Search
- [x] #37 Favicon
- [x] #38 Page layout
- [x] #39 Side navigation styling
- [x] #40 Homepage (re-create current Browse functionality)

**Comment by davidschober** [comment]
This looks awesome! Thanks Adam...

**Comment by davidschober** [comment]
@adamjarling you ready to close this big issue? It looks like we're down to some bugs.

**Comment by adamjarling** [comment]
Yea, as more trickle in we can just handle separately.  This served it's purpose as a big net checklist.
