### ISSUE TITLE
Move 6.3 to production

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#333]
### Description
Merge Avalon 6.3.2 into production.

### Done Looks Like
Avalon 6.3 is moved into production.

### Tasks
- [ ] Get down time #343
- [x] turn off RTMP #342
- [x] Final testing #344
- [ ] Delete derivatives #342
- [x] Move over new config variables for throttling from staging to webapp and workers

**Comment by adamjarling** [comment]
Move turn off RTMP and delete derivatives into separate issues.
