### ISSUE TITLE
Full regression testing of Staging 6/19 am

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#386]
## Special Note 
 change staging bucket name in Cyberduck from `avr-masterfiles-staging-rd56wk8` to `stack-s-avr-masterfiles`

## Testing
Using the spreadsheet below, please complete assigned sections and kick off bugs. 
### [create copy of the testing template](https://docs.google.com/spreadsheets/d/1v-K4NWEPyERabHHCMPADI79P-d1FAu2_fqy_dgfngdI/copy)

And save it to [Repository and Digital Curation Shared Docs/TestScripts/completed_scripts](https://docs.google.com/spreadsheets/d/13cWzYMIMRZJ877_5Lbpf8VQNl2628jbq8kWnlsRJM3w/edit?usp=sharing/copy) using YYYYMMMDD_lastname as a filename. 

## Bugs found

For each bug found, add a new github issue to [nulib/avalon](https://github.com/nulib/avalon/issues) and label it "bug". 

Bugs will be triaged and dealt with as necessary. 
## Test on 

[AVR staging](http://avr.stack.rdc-staging.library.northwestern.edu/) 
[Canvas staging](https://canvas.northwestern.edu/)

## Example Comment when you're done with a task

Hi, I tested section 1 -- script and notes in:  [link to your copy of testing script here]

FYI I found bugs `github issues number`

## Tasks and assignees

- [x] 1. Create private collection 
- [x] 2. Web Ingest an item
- [ ] 3. LTI
- [x] 4. Embed
- [x] 5. Batch ingest
- [x] 6. Structural Metadata
- [x] 7. Create group
- [x] 8. Bulk actions
- [x] 9. Search/playback
- [x] 10. Accessibility
- [x] 11. Playback - sticky quality
- [x] 12. Captions
- [ ] 13. IP based access control
- [x] 14. Start/end dates for access (Lease)
- [x] 15. Playlists and Items
- [x] 16. Zoom Scrubber
- [x] 17. Ensure content is there.

**Comment by jenyoung** [comment]
bug tickets: 
#388 
#389 
#390

**Comment by davidschober** [comment]
Done except for LTI as we can't test that in staging currently.
