### ISSUE TITLE
Alter test template for new AVR 

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#49]
We need a new testing script for Avalon 6.0 - below is the one used for the Avalon project. We need to alter for local testing.

## **DONE LOOKS LIKE**
- script below is altered for NUL testing

## Testing

Using the spreadsheet below, please complete assigned sections and kick off bugs. 
### [create copy of the testing template](https://docs.google.com/spreadsheets/d/1v-K4NWEPyERabHHCMPADI79P-d1FAu2_fqy_dgfngdI/copy)

And save it to [Avalon Test Scripts/completed\_tests](https://drive.google.com/drive/folders/0B3iiRmWEFfdYRHpBZ1BTY2lHZjQ) using YYYYMMMDD_lastname as a filename. 

## Bugs found

For each bug found, add a new github issue to [avalon](https://github.com/avalonmediasystem/avalon/issues) and label it "bug". 

Bugs will be triaged and dealt with as necessary. 

## Completed tests
Please put completed test script in [completed tests](https://drive.google.com/drive/folders/0B3iiRmWEFfdYRHpBZ1BTY2lHZjQ/copy)

## Test on 

FILL IN SERVER NAME

## Example Comment when you're done with a task

Hi all, I section 1 script and notes in: https://docs.google.com/spreadsheets/d/1v-K4NWEPyERabHHCMPADI79P-d1FAu2_fqy_dgfngdI/edit#gid=1730858809

FYI I found bugs #1, #1, #1

## Tasks and assignees

delete as necessary if not doing full testing. .

- [ ] 1. Create private collection 
- [ ] 2. Web Ingest an item
- [ ] 3. LTI
- [ ] 4. Embed
- [ ] 5. Batch ingest
- [ ] 6. Structural Metadata
- [ ] 7. Create group
- [ ] 8. Bulk actions
- [ ] 9. Search/playback
- [ ] 10. Accessibility
- [ ] 11. Playback - sticky quality
- [ ] 12. Captions
- [ ] 13. IP based access control
- [ ] 14. Start/end dates for access (Lease)
- [ ] 15. Playlists and Items
- [ ] 16. Zoom Scrubber

**Comment by jenyoung** [comment]
@davidschober this version is for R5. is there an R6 version?

**Comment by jenyoung** [comment]
closing. use #73
