### ISSUE TITLE
Full Regression Testing Avalon 6.0 (NU)

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#73]
Using the spreadsheet below, please complete assigned sections and kick off bugs. 
### [create copy of the testing template](https://docs.google.com/spreadsheets/d/1v-K4NWEPyERabHHCMPADI79P-d1FAu2_fqy_dgfngdI/copy)

And save it to [Repository and Digital Curation Shared Docs/TestScripts/completed_scripts](https://docs.google.com/spreadsheets/d/13cWzYMIMRZJ877_5Lbpf8VQNl2628jbq8kWnlsRJM3w/edit?usp=sharing/copy) using YYYYMMMDD_lastname as a filename. 

## Bugs found

For each bug found, add a new github issue to [nulib/avalon](https://github.com/nulib/avalon/issues) and label it "bug". 

Bugs will be triaged and dealt with as necessary. 

## Test on 

http://avalon.repo.rdc.library.northwestern.edu/

## Example Comment when you're done with a task

Hi, I tested section 1 -- script and notes in:  [link to your copy of testing script here]

FYI I found bugs #1, #1, #1

## Tasks and assignees - @egilchrist and @laura-alagna will be testing June -7

- [ ] 1. Create private collection 
- [ ] 2. Web Ingest an item
- [ ] 3. LTI
- [ ] 4. Embed
- [ ] 5. Batch ingest
- [ ] 6. Structural Metadata
- [ ] 7. Create group
- [ ] 8. Bulk actions
- [ ] 9. Search/playback
- [ ] 10. Accessibility
- [ ] 11. Playback - sticky quality
- [ ] 12. Captions
- [ ] 13. IP based access control
- [ ] 14. Start/end dates for access (Lease)
- [ ] 15. Playlists and Items
- [ ] 16. Zoom Scrubber
